import 'package:flutter/material.dart';
import 'package:skeletonizer/skeletonizer.dart';

import '../../../../data/repository/repository.dart';

class AutoGeneratedInvoiceField extends ConsumerWidget {
  const AutoGeneratedInvoiceField({
    super.key,
    this.autoGenerate = true,
    required this.controller,
    required this.invoiceType,
    this.decoration,
  });
  final bool autoGenerate;
  final TextEditingController controller;
  final AutoGeneratedInvoiceType invoiceType;
  final InputDecoration? decoration;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    if (!autoGenerate) {
      return TextFormField(
        controller: controller,
        decoration: decoration,
        readOnly: true,
      );
    }

    var _invoiceAsync = ref.watch(
      _autoGenerateInvoiceProvider(invoiceType.key),
    );

    return _invoiceAsync.when(
      skipLoadingOnRefresh: false,
      skipLoadingOnReload: false,
      data: (data) {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          controller.text = data ?? '';
        });
        return TextFormField(
          controller: controller,
          decoration: decoration,
          readOnly: true,
        );
      },
      error: (error, stackTrace) {
        return TextFormField(
          controller: controller,
          decoration: decoration?.copyWith(
            suffixIcon: IconButton(
              onPressed: () {
                _invoiceAsync = ref.refresh(
                  _autoGenerateInvoiceProvider(invoiceType.key),
                );
              },
              icon: const Icon(Icons.refresh),
            ),
          ),
          readOnly: true,
          forceErrorText: error.toString(),
        );
      },
      loading: () {
        return Skeletonizer(
          child: TextFormField(
            decoration: decoration,
            readOnly: true,
          ),
        );
      },
    );
  }
}

enum AutoGeneratedInvoiceType {
  sale('sales'),
  purchase('purchases'),
  dueCollect('due_collects'),
  saleReturn('sales_return'),
  purchaseReturn('purchases_return');

  final String key;
  const AutoGeneratedInvoiceType(this.key);
}

final _autoGenerateInvoiceProvider =
    FutureProvider.autoDispose.family<String?, String>(
  (ref, arg) => Future.microtask(
    () => ref.read(userRepositoryProvider.notifier).getNextInvoice(arg),
  ),
);
