import 'package:auto_route/auto_route.dart';
import 'package:expansion_widget/expansion_widget.dart';
import 'package:fdevs_fitkit/fdevs_fitkit.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_slidable/flutter_slidable.dart';
import 'package:form_builder_validators/form_builder_validators.dart';
import 'package:hugeicons_pro/hugeicons.dart';

import '../../../../../i18n/strings.g.dart';
import '../../../../core/core.dart';
import '../../../../data/repository/repository.dart';
import '../../../../widgets/widgets.dart';
import '../../../common/widgets/widgets.dart'
    show PaymentSelectorFormField, ThermalPreview, SharedWidgets, AutoGeneratedInvoiceField, AutoGeneratedInvoiceType;
import '../../../../routes/app_routes.gr.dart';
import '../components/components.dart';

part '_manage_purchase_view_provider.dart';

@RoutePage()
class ManagePurchaseView extends ConsumerStatefulWidget {
  const ManagePurchaseView({super.key, this.editModel});
  final Purchase? editModel;
  bool get isEditMode => editModel != null;

  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _ManagePurchaseViewState();
}

class _ManagePurchaseViewState extends ConsumerState<ManagePurchaseView> {
  @override
  void initState() {
    if (widget.isEditMode) {
      ref.read(managePurchaseViewProvider).initEdit(widget.editModel!);
    }
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final controller = ref.watch(managePurchaseViewProvider);
    final _supplierListAsync = ref.watch(supplierDropdownProvider);

    final _theme = Theme.of(context);

    return FormWrapper(
      builder: (formContext) {
        return Scaffold(
          appBar: CustomAppBar(
            title: Text(
              // widget.isEditMode ? 'Edit Purchase' : 'Add New Purchase',
              widget.isEditMode ? context.t.pages.purchase.editPurchase : context.t.pages.purchase.title,
            ),
          ),
          body: SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Column(
              children: [
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Invoice Number
                    Expanded(
                      child: AutoGeneratedInvoiceField(
                        autoGenerate: !widget.isEditMode,
                        controller: controller.invoiceNumberController,
                        invoiceType: AutoGeneratedInvoiceType.purchase,
                        decoration: InputDecoration(
                          // labelText: 'Bill No',
                          labelText: context.t.form.bill.label,
                          // hintText: 'P-00001',
                          hintText: context.t.form.bill.hint,
                        ),
                      ),
                    ),
                    const SizedBox.square(dimension: 16),

                    // Invoice Date
                    Expanded(
                      child: DateFormField(
                        controller: controller.invoiceDateController,
                        dateFormat: CustomDateFormat('dd/MM/yyyy'),
                        decoration: InputDecoration(
                          // labelText: 'Date*',
                          labelText: "${context.t.common.date}*",
                          hintText: 'dd/mm/yyyy',
                        ),
                        validator: FormBuilderValidators.compose([
                          FormBuilderValidators.required(),
                        ]),
                      ),
                    ),
                  ],
                ),
                const SizedBox.square(dimension: 20),

                // Supplier Dropdown
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      child: AsyncCustomDropdown<int, PartyList>(
                        asyncData: _supplierListAsync,
                        decoration: InputDecoration(
                          // labelText: 'Supplier*',
                          labelText: "${context.t.form.supplier.label}*",
                          // hintText: 'Select Supplier',
                          hintText: context.t.form.supplier.hint,
                        ),
                        value: controller.dropdownValues['supplier_id'],
                        items: _supplierListAsync.when(
                          data: (data) => [
                            ...?data.data?.data?.map((supplier) {
                              return CustomDropdownMenuItem<int>(
                                value: supplier.id,
                                label: TextSpan(text: supplier.name ?? "N/A"),
                              );
                            }),
                          ],
                          error: (e, s) => [],
                          loading: () => [],
                        ),
                        onChanged: (v) => controller.handleDropdownChange(
                          MapEntry('supplier_id', v),
                        ),
                        validator: FormBuilderValidators.required(
                          // errorText: 'Please select a supplier',
                          errorText: context.t.form.supplier.extra.required,
                        ),
                      ),
                    ),
                    const SizedBox.square(dimension: 10),

                    // Add Supplier Button
                    CustomSearchFieldActionButton.custom(
                      icon: const Icon(Icons.add),
                      onPressed: () async {
                        return context.router.push<void>(
                          ManagePartyRoute(),
                        );
                      },
                      style: CustomSearchFieldActionButton.themeColored(
                        context,
                        isFilled: true,
                      ),
                    ),
                  ],
                ),
                const SizedBox.square(dimension: 16),

                // Add Items Button
                SizedBox.fromSize(
                  size: const Size.fromHeight(40),
                  child: FilledButton(
                    onPressed: () async {
                      return _handleAddIngredient(context);
                    },
                    style: FilledButton.styleFrom(
                      foregroundColor: _theme.colorScheme.primary,
                      backgroundColor: _theme.colorScheme.primary.withValues(
                        alpha: 0.10,
                      ),
                    ),
                    // child: const Text('+ Add Items'),
                    child: Text('+ ${context.t.common.addItems}'),
                  ),
                ),
                const SizedBox.square(dimension: 12),

                // Added Items
                ExpansionWidget.autoSaveState(
                  initiallyExpanded: true,
                  titleBuilder: (av, ev, ie, tf) {
                    return InkWell(
                      onTap: () => tf(animated: true),
                      child: Container(
                        padding: const EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          color: _theme.colorScheme.primary.withValues(
                            alpha: 0.1,
                          ),
                          borderRadius: ie ? BorderRadius.vertical(top: Radius.circular(6)) : BorderRadius.circular(6),
                          border: ie
                              ? BorderDirectional(
                                  start: Divider.createBorderSide(context),
                                  top: Divider.createBorderSide(context),
                                  end: Divider.createBorderSide(context),
                                )
                              : Border.fromBorderSide(
                                  Divider.createBorderSide(context),
                                ),
                        ),
                        child: DefaultTextStyle.merge(
                          style: _theme.textTheme.bodyLarge?.copyWith(
                            fontWeight: FontWeight.w500,
                          ),
                          child: Row(
                            children: [
                              Transform.rotate(
                                angle: av * (22 / 7),
                                child: const Icon(
                                  Icons.keyboard_arrow_down_rounded,
                                ),
                              ),
                              const SizedBox.square(dimension: 6),
                              // const Expanded(child: Text('Item Added')),
                              Expanded(child: Text(context.t.common.itemAdded)),
                              // const Text('Amount', textAlign: TextAlign.end)
                              Text(context.t.common.amount, textAlign: TextAlign.end),
                            ],
                          ),
                        ),
                      ),
                    );
                  },
                  content: DecoratedBox(
                    decoration: BoxDecoration(
                      border: Border.fromBorderSide(
                        Divider.createBorderSide(context),
                      ),
                    ),
                    child: Builder(
                      builder: (_) {
                        if (controller.purchaseItems.isEmpty) {
                          return Padding(
                            padding: const EdgeInsets.only(top: 16),
                            child: EmptyWidget(
                              // replaceDefault: false,
                              emptyBuilder: (_) {
                                return RetryButtons.scrollView(
                                  // 'No Items added',
                                  context.t.common.noItemAdded,
                                  onRetry: () async {
                                    return _handleAddIngredient(context);
                                  },
                                  // buttonText: 'Add items',
                                  buttonText: context.t.common.addItems,
                                  icon: const Icon(Icons.add),
                                );
                              },
                            ),
                          );
                        }

                        return ListView.builder(
                          shrinkWrap: true,
                          physics: const NeverScrollableScrollPhysics(),
                          itemCount: controller.purchaseItems.length,
                          itemBuilder: (_, index) {
                            final item = controller.purchaseItems[index];
                            final _isLast = index == controller.purchaseItems.length - 1;

                            return DecoratedBox(
                              decoration: BoxDecoration(
                                border: _isLast
                                    ? null
                                    : Border(
                                        bottom: Divider.createBorderSide(context),
                                      ),
                              ),
                              child: Slidable(
                                key: ValueKey(index),
                                endActionPane: ActionPane(
                                  closeThreshold: 0.25,
                                  openThreshold: 0.25,
                                  motion: const ScrollMotion(),
                                  extentRatio: 0.25,
                                  children: [
                                    SlidableAction(
                                      onPressed: (_) async {
                                        return _handleEditItem(context, item);
                                      },
                                      padding: EdgeInsets.zero,
                                      backgroundColor: DAppColors.kSuccess.withValues(
                                        alpha: 0.10,
                                      ),
                                      foregroundColor: DAppColors.kSuccess,
                                      icon: HugeIconsStroke.pencilEdit02,
                                    ),
                                    SlidableAction(
                                      onPressed: (_) {
                                        return controller.handleAddingToCart(
                                          item.copyWith(quantity: 0),
                                        );
                                      },
                                      padding: EdgeInsets.zero,
                                      backgroundColor: DAppColors.kError.withValues(
                                        alpha: 0.10,
                                      ),
                                      foregroundColor: DAppColors.kError,
                                      icon: HugeIconsStroke.delete03,
                                    ),
                                  ],
                                ),
                                child: PurchaseItemCard(
                                  title: TextSpan(text: item.name),
                                  subtitle: TextSpan(
                                    text:
                                        '${item.quantity.commaSeparated()}${item.unit?.unitName ?? ""} x ${(item.unitPrice ?? 0).quickCurrency()}',
                                  ),
                                  price: item.totalPrice,
                                ),
                              ),
                            );
                          },
                        );
                      },
                    ),
                  ),
                ),
                const SizedBox.square(dimension: 16),

                // Amount Overview
                DefaultTextStyle.merge(
                  style: _theme.textTheme.bodyLarge?.copyWith(
                    fontWeight: FontWeight.w500,
                  ),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Subtotal
                      Row(
                        children: [
                          // const Expanded(child: Text('Sub Total')),
                          Expanded(child: Text(context.t.common.subTotal)),
                          Expanded(
                            child: Text(
                              controller.subtotalAmount.quickCurrency(),
                              textAlign: TextAlign.end,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox.square(dimension: 8),

                      // Discount
                      Row(
                        children: [
                          Expanded(
                            child: Text(
                              // 'Discount ${controller.discountModifier.valueInPercent.commaSeparated()}%',
                              '${context.t.common.discount} ${controller.discountModifier.valueInPercent.commaSeparated()}%',
                              style: TextStyle(
                                color: _theme.paragraphColor,
                                fontWeight: FontWeight.normal,
                              ),
                            ),
                          ),
                          SizedBox(
                            width: 75,
                            child: RateSelectorFormField(
                              baseAmount: controller.subtotalAmount,
                              showModifierSelector: false,
                              selectedModifier: controller.discountModifier,
                              controller: controller.discountController,
                              onChanged: controller.handleDiscountModifierChange,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox.square(dimension: 8),

                      // VAT
                      Row(
                        children: [
                          Expanded(
                            child: Text(
                              // 'VAT %',
                              '${context.t.common.vat} %',
                              style: TextStyle(
                                color: _theme.paragraphColor,
                                fontWeight: FontWeight.normal,
                              ),
                            ),
                          ),
                          SizedBox(
                            width: 75,
                            child: NumberFormField(
                              controller: controller.vatController,
                              textAlign: TextAlign.end,
                              decoration: CustomFieldStyles.kUnderlined(
                                context,
                                hinText: 'Ex: 10%',
                              ),
                              validator: FormBuilderValidators.compose([
                                FormBuilderValidators.positiveNumber(
                                  checkNullOrEmpty: false,
                                ),
                              ]),
                              onChanged: (_) => controller.update(),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox.square(dimension: 8),

                      // Total Amount
                      Row(
                        children: [
                          // const Expanded(child: Text('Total')),
                          Expanded(child: Text(context.t.common.total)),
                          Expanded(
                            child: Text(
                              controller.netPayableAmount.quickCurrency(),
                              textAlign: TextAlign.end,
                              style: TextStyle(
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox.square(dimension: 8),

                      // Pay Amount
                      Row(
                        children: [
                          Expanded(
                            child: Text.rich(
                              TextSpan(
                                children: [
                                  TextSpan(
                                    // text: 'Pay Amount',
                                    text: context.t.common.payAmount,
                                    recognizer: TapGestureRecognizer()
                                      ..onTap = () {
                                        return controller.toggleIsPaid(
                                          !controller.isPaid,
                                        );
                                      },
                                  ),
                                  WidgetSpan(
                                    alignment: PlaceholderAlignment.middle,
                                    child: SizedBox.square(
                                      dimension: 16,
                                      child: Checkbox(
                                        value: controller.isPaid,
                                        onChanged: controller.toggleIsPaid,
                                      ),
                                    ).fMarginOnly(left: 8),
                                  ),
                                ],
                                style: TextStyle(
                                  color: _theme.paragraphColor,
                                  fontWeight: FontWeight.normal,
                                ),
                              ),
                            ),
                          ),
                          SizedBox(
                            width: 75,
                            child: NumberFormField(
                              controller: controller.payAmountController,
                              textAlign: TextAlign.end,
                              decoration: CustomFieldStyles.kUnderlined(
                                context,
                                // hinText: 'Ex: \$100',
                                hinText: context.t.form.items.totalSalePrice.hint,
                              ),
                              validator: FormBuilderValidators.compose([
                                FormBuilderValidators.positiveNumber(
                                  checkNullOrEmpty: false,
                                ),
                              ]),
                              onChanged: (v) {
                                SharedWidgets.warnIfExeedLimit(
                                  context,
                                  controller.netPayableAmount,
                                  num.tryParse(v) ?? 0,
                                  // message: 'Received amount should not be greater than payable amount',
                                  message: context.t.exceptions.exceedsPaymentAmount,
                                  onExeeded: controller.payAmountController.clear,
                                );
                                return controller.update();
                              },
                            ),
                          ),
                        ],
                      ),
                      const SizedBox.square(dimension: 8),

                      // Due Amount
                      Row(
                        children: [
                          Expanded(
                            child: Text(
                              // 'Due Amount',
                              context.t.common.dueAmount,
                              style: TextStyle(
                                color: _theme.paragraphColor,
                                fontWeight: FontWeight.normal,
                              ),
                            ),
                          ),
                          Expanded(
                            child: Text(
                              controller.dueAmount.quickCurrency(),
                              textAlign: TextAlign.end,
                              style: TextStyle(fontWeight: FontWeight.normal),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          bottomNavigationBar: BottomNavWrapper(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                // Payment Method
                PaymentSelectorFormField(
                  autoSelectFirst: !widget.isEditMode,
                  selectedPaymentMethod: controller.dropdownValues['payment_id'],
                  onChanged: (value) {
                    return controller.handleDropdownChange(
                      MapEntry('payment_id', value),
                    );
                  },
                ),
                const SizedBox.square(dimension: 14),

                // Action Button
                ElevatedButton(
                  onPressed: () async {
                    if (FormWrapper.validate(formContext)) {
                      return _handleFormSubmit(context);
                    }
                  },
                  // child: const Text('Save & Print'),
                  child: Text(context.t.common.saveNPrint),
                ),
              ],
            ),
          ),
        );
      },
    ).unfocusPrimary();
  }

  Future<void> _handleFormSubmit(BuildContext context) async {
    final _result = await showAsyncLoadingOverlay(
      context,
      asyncFunction: () => ref.read(managePurchaseViewProvider).handleManagePurchase(widget.editModel),
    );

    if (context.mounted) {
      if (_result.isFailure) {
        showCustomSnackBar(
          context,
          content: Text(_result.left!),
          customSnackBarType: CustomOverlayType.error,
        );
        return;
      }

      context.router.pop();
      context.router.push(
        InvoicePreviewRoute(
          previewType: ThermalPreview(
            SalePurchaseThermalInvoiceData.fromPurchase(_result.right!.data!),
          ),
        ),
      );
    }
  }

  Future<void> _handleAddIngredient(BuildContext context) async {
    final _result = await context.router.push<IngredientCartItem>(
      IngredientListRoute(purchaseSelector: true),
    );

    if (_result != null) {
      final controller = ref.read(managePurchaseViewProvider);
      return controller.handleAddingToCart(_result);
    }
  }

  Future<void> _handleEditItem(
    BuildContext context,
    IngredientCartItem ingredient,
  ) async {
    final _result = await showSelectedIngredientModal(context, ingredient);

    if (_result != null) {
      final controller = ref.read(managePurchaseViewProvider);
      return controller.handleAddingToCart(_result);
    }
  }
}

class PurchaseItemCard extends StatelessWidget {
  const PurchaseItemCard({
    super.key,
    required this.title,
    required this.subtitle,
    this.price = 0,
  });
  final InlineSpan title;
  final InlineSpan subtitle;
  final num price;

  @override
  Widget build(BuildContext context) {
    final _theme = Theme.of(context);
    return ListTile(
      title: Text.rich(title),
      subtitle: Text.rich(subtitle),
      trailing: Text(price.quickCurrency()),
      titleTextStyle: _theme.textTheme.bodyLarge?.copyWith(
        fontWeight: FontWeight.w500,
      ),
      leadingAndTrailingTextStyle: _theme.textTheme.bodyLarge?.copyWith(
        fontWeight: FontWeight.w500,
      ),
      contentPadding: EdgeInsets.symmetric(horizontal: 8),
    );
  }
}
